Update LoginViewController.swift
Guboneui/GuestHoust-User pull request #21
Opened 2023-10-24 18:05 UTC by minneee

[DESIGN] 로그인 첫페이지 UI작업

### **배경**
사용자가 어떤 방법으로 로그인/회원가입을 할 지 선택할 수 있는 화면
<br>
<br>
<br>

### **요구사항**
<img src="https://github.com/Guboneui/GuestHoust-User/assets/86248191/e5ad0aa7-0c43-43aa-b743-2cf85f44adb7" width="30%" />

### **결과**
<img src="https://github.com/Guboneui/GuestHoust-User/assets/86248191/9e04d36e-16e7-4c4d-938a-10df0aca91e2" width="30%" />

### **todo**
로고가 없어서 회색 뷰로 만들어놔서 로고 생기면 변경해야합니다.
비지니스/관리자 회원가입 기능 추가할 때 추가 디자인 작업 필요합니다.

2023-10-24 18:44 UTC, Guboneui requested changes

2023-10-24 18:44 UTC, Guboneui commented on Feature/Login/Sources/LoginViewController.swift
> +      make.height.equalTo(54)
`SocialLoginButton`의 크기가 이미 정해져 있고, 이를 배경으로 StackView 내부에 들어가기 때문에 별도의 높이 지정이 필요 없습니다

2023-10-30 11:47 UTC, Donggaem commented on Feature/Login/Sources/LoginViewController.swift
> +
무분별한 줄 바꿈은 지양해주세요 @minneee

2023-10-31 10:46 UTC, Guboneui commented on Feature/Login/Sources/LoginViewController.swift
> +      make.top.equalToSuperview().offset(415)
작은 화면에서 UI 확인 해주세염 @minneee

2023-10-31 11:17 UTC, Guboneui approved these changes

2023-10-31 11:17 UTC, Guboneui commented on Feature/Login/Sources/LoginViewController.swift
> +  private let loginStackView: UIStackView = UIStackView().then {
변수명 바꾸는거 좋아용

2023-10-31 11:17 UTC, Guboneui commented on Feature/Login/Sources/LoginViewController.swift
> +  private enum Metric {
코드 통일성을 위해서, 되도록이면 타입을 명시해 주도록 합시당

2023-10-31 11:17 UTC, Guboneui commented on Feature/Login/Sources/LoginViewController.swift
> +    loginStackView.addArrangedSubview(naverLoginButton)
이 부분 전에 얘기했었지만, 정확한 정답은 없는거니까.
동겸이 코드 한번 봐볼래? 그런 방법도 있다는 거 한번 보면 좋을 것 같아

2023-10-31 11:25 UTC, merged